// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type FloatingIPAssociateInitParameters struct {

	// optional string →  One of the port's IP addresses.
	// One of the port's IP addresses.
	FixedIP *string `json:"fixedIp,omitempty" tf:"fixed_ip,omitempty"`

	// optional string →  The region in which to obtain the Networking client. A Networking client is needed to create a floating IP that can be used with another networking resource, such as a load balancer. If omitted, the region argument of the provider is used. Changing this creates a new floating IP (which may or may not have a different address).
	// The region in which to obtain the Networking client. A Networking client is needed to create a floating IP that can be used with another networking resource, such as a load balancer. If omitted, the `region` argument of the provider is used. Changing this creates a new floating IP (which may or may not have a different address).
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// optional string →  SDN to use for this resource. Must be one of following: "neutron", "sprut". Default value is project's default SDN.
	// SDN to use for this resource. Must be one of following: "neutron", "sprut". Default value is project's default SDN.
	Sdn *string `json:"sdn,omitempty" tf:"sdn,omitempty"`
}

type FloatingIPAssociateObservation struct {

	// optional string →  One of the port's IP addresses.
	// One of the port's IP addresses.
	FixedIP *string `json:"fixedIp,omitempty" tf:"fixed_ip,omitempty"`

	// required string →  IP Address of an existing floating IP.
	// IP Address of an existing floating IP.
	FloatingIP *string `json:"floatingIp,omitempty" tf:"floating_ip,omitempty"`

	// string →  ID of the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// required string →  ID of an existing port with at least one IP address to associate with this floating IP.
	// ID of an existing port with at least one IP address to associate with this floating IP.
	PortID *string `json:"portId,omitempty" tf:"port_id,omitempty"`

	// optional string →  The region in which to obtain the Networking client. A Networking client is needed to create a floating IP that can be used with another networking resource, such as a load balancer. If omitted, the region argument of the provider is used. Changing this creates a new floating IP (which may or may not have a different address).
	// The region in which to obtain the Networking client. A Networking client is needed to create a floating IP that can be used with another networking resource, such as a load balancer. If omitted, the `region` argument of the provider is used. Changing this creates a new floating IP (which may or may not have a different address).
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// optional string →  SDN to use for this resource. Must be one of following: "neutron", "sprut". Default value is project's default SDN.
	// SDN to use for this resource. Must be one of following: "neutron", "sprut". Default value is project's default SDN.
	Sdn *string `json:"sdn,omitempty" tf:"sdn,omitempty"`
}

type FloatingIPAssociateParameters struct {

	// optional string →  One of the port's IP addresses.
	// One of the port's IP addresses.
	// +kubebuilder:validation:Optional
	FixedIP *string `json:"fixedIp,omitempty" tf:"fixed_ip,omitempty"`

	// required string →  IP Address of an existing floating IP.
	// IP Address of an existing floating IP.
	// +crossplane:generate:reference:type=FloatingIP
	// +crossplane:generate:reference:extractor=github.com/viletay/provider-vkcs/config/network.ExtractSpecAddress()
	// +kubebuilder:validation:Optional
	FloatingIP *string `json:"floatingIp,omitempty" tf:"floating_ip,omitempty"`

	// Reference to a FloatingIP to populate floatingIp.
	// +kubebuilder:validation:Optional
	FloatingIPRef *v1.Reference `json:"floatingIpRef,omitempty" tf:"-"`

	// Selector for a FloatingIP to populate floatingIp.
	// +kubebuilder:validation:Optional
	FloatingIPSelector *v1.Selector `json:"floatingIpSelector,omitempty" tf:"-"`

	// required string →  ID of an existing port with at least one IP address to associate with this floating IP.
	// ID of an existing port with at least one IP address to associate with this floating IP.
	// +crossplane:generate:reference:type=Port
	// +kubebuilder:validation:Optional
	PortID *string `json:"portId,omitempty" tf:"port_id,omitempty"`

	// Reference to a Port to populate portId.
	// +kubebuilder:validation:Optional
	PortIDRef *v1.Reference `json:"portIdRef,omitempty" tf:"-"`

	// Selector for a Port to populate portId.
	// +kubebuilder:validation:Optional
	PortIDSelector *v1.Selector `json:"portIdSelector,omitempty" tf:"-"`

	// optional string →  The region in which to obtain the Networking client. A Networking client is needed to create a floating IP that can be used with another networking resource, such as a load balancer. If omitted, the region argument of the provider is used. Changing this creates a new floating IP (which may or may not have a different address).
	// The region in which to obtain the Networking client. A Networking client is needed to create a floating IP that can be used with another networking resource, such as a load balancer. If omitted, the `region` argument of the provider is used. Changing this creates a new floating IP (which may or may not have a different address).
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// optional string →  SDN to use for this resource. Must be one of following: "neutron", "sprut". Default value is project's default SDN.
	// SDN to use for this resource. Must be one of following: "neutron", "sprut". Default value is project's default SDN.
	// +kubebuilder:validation:Optional
	Sdn *string `json:"sdn,omitempty" tf:"sdn,omitempty"`
}

// FloatingIPAssociateSpec defines the desired state of FloatingIPAssociate
type FloatingIPAssociateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FloatingIPAssociateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FloatingIPAssociateInitParameters `json:"initProvider,omitempty"`
}

// FloatingIPAssociateStatus defines the observed state of FloatingIPAssociate.
type FloatingIPAssociateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FloatingIPAssociateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// FloatingIPAssociate is the Schema for the FloatingIPAssociates API. Associates a Floating IP to a Port
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vkcs}
type FloatingIPAssociate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FloatingIPAssociateSpec   `json:"spec"`
	Status            FloatingIPAssociateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FloatingIPAssociateList contains a list of FloatingIPAssociates
type FloatingIPAssociateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FloatingIPAssociate `json:"items"`
}

// Repository type metadata.
var (
	FloatingIPAssociate_Kind             = "FloatingIPAssociate"
	FloatingIPAssociate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FloatingIPAssociate_Kind}.String()
	FloatingIPAssociate_KindAPIVersion   = FloatingIPAssociate_Kind + "." + CRDGroupVersion.String()
	FloatingIPAssociate_GroupVersionKind = CRDGroupVersion.WithKind(FloatingIPAssociate_Kind)
)

func init() {
	SchemeBuilder.Register(&FloatingIPAssociate{}, &FloatingIPAssociateList{})
}
