// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SubnetRouteInitParameters struct {

	// required string →  CIDR block to match on the packet’s destination IP. Changing this creates a new routing entry.
	// CIDR block to match on the packet’s destination IP. Changing this creates a new routing entry.
	DestinationCidr *string `json:"destinationCidr,omitempty" tf:"destination_cidr,omitempty"`

	// required string →  IP address of the next hop gateway. Changing this creates a new routing entry.
	// IP address of the next hop gateway. Changing this creates a new routing entry.
	NextHop *string `json:"nextHop,omitempty" tf:"next_hop,omitempty"`

	// optional string →  The region in which to obtain the networking client. A networking client is needed to configure a routing entry on a subnet. If omitted, the region argument of the provider is used. Changing this creates a new routing entry.
	// The region in which to obtain the networking client. A networking client is needed to configure a routing entry on a subnet. If omitted, the `region` argument of the provider is used. Changing this creates a new routing entry.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// optional string →  SDN to use for this resource. Must be one of following: "neutron", "sprut". Default value is project's default SDN.
	// SDN to use for this resource. Must be one of following: "neutron", "sprut". Default value is project's default SDN.
	Sdn *string `json:"sdn,omitempty" tf:"sdn,omitempty"`
}

type SubnetRouteObservation struct {

	// required string →  CIDR block to match on the packet’s destination IP. Changing this creates a new routing entry.
	// CIDR block to match on the packet’s destination IP. Changing this creates a new routing entry.
	DestinationCidr *string `json:"destinationCidr,omitempty" tf:"destination_cidr,omitempty"`

	// string →  ID of the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// required string →  IP address of the next hop gateway. Changing this creates a new routing entry.
	// IP address of the next hop gateway. Changing this creates a new routing entry.
	NextHop *string `json:"nextHop,omitempty" tf:"next_hop,omitempty"`

	// optional string →  The region in which to obtain the networking client. A networking client is needed to configure a routing entry on a subnet. If omitted, the region argument of the provider is used. Changing this creates a new routing entry.
	// The region in which to obtain the networking client. A networking client is needed to configure a routing entry on a subnet. If omitted, the `region` argument of the provider is used. Changing this creates a new routing entry.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// optional string →  SDN to use for this resource. Must be one of following: "neutron", "sprut". Default value is project's default SDN.
	// SDN to use for this resource. Must be one of following: "neutron", "sprut". Default value is project's default SDN.
	Sdn *string `json:"sdn,omitempty" tf:"sdn,omitempty"`

	// required string →  ID of the subnet this routing entry belongs to. Changing this creates a new routing entry.
	// ID of the subnet this routing entry belongs to. Changing this creates a new routing entry.
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`
}

type SubnetRouteParameters struct {

	// required string →  CIDR block to match on the packet’s destination IP. Changing this creates a new routing entry.
	// CIDR block to match on the packet’s destination IP. Changing this creates a new routing entry.
	// +kubebuilder:validation:Optional
	DestinationCidr *string `json:"destinationCidr,omitempty" tf:"destination_cidr,omitempty"`

	// required string →  IP address of the next hop gateway. Changing this creates a new routing entry.
	// IP address of the next hop gateway. Changing this creates a new routing entry.
	// +kubebuilder:validation:Optional
	NextHop *string `json:"nextHop,omitempty" tf:"next_hop,omitempty"`

	// optional string →  The region in which to obtain the networking client. A networking client is needed to configure a routing entry on a subnet. If omitted, the region argument of the provider is used. Changing this creates a new routing entry.
	// The region in which to obtain the networking client. A networking client is needed to configure a routing entry on a subnet. If omitted, the `region` argument of the provider is used. Changing this creates a new routing entry.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// optional string →  SDN to use for this resource. Must be one of following: "neutron", "sprut". Default value is project's default SDN.
	// SDN to use for this resource. Must be one of following: "neutron", "sprut". Default value is project's default SDN.
	// +kubebuilder:validation:Optional
	Sdn *string `json:"sdn,omitempty" tf:"sdn,omitempty"`

	// required string →  ID of the subnet this routing entry belongs to. Changing this creates a new routing entry.
	// ID of the subnet this routing entry belongs to. Changing this creates a new routing entry.
	// +crossplane:generate:reference:type=Subnet
	// +kubebuilder:validation:Optional
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// Reference to a Subnet to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDRef *v1.Reference `json:"subnetIdRef,omitempty" tf:"-"`

	// Selector for a Subnet to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDSelector *v1.Selector `json:"subnetIdSelector,omitempty" tf:"-"`
}

// SubnetRouteSpec defines the desired state of SubnetRoute
type SubnetRouteSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SubnetRouteParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SubnetRouteInitParameters `json:"initProvider,omitempty"`
}

// SubnetRouteStatus defines the observed state of SubnetRoute.
type SubnetRouteStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SubnetRouteObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// SubnetRoute is the Schema for the SubnetRoutes API. Creates a routing entry on a VKCS subnet.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vkcs}
type SubnetRoute struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.destinationCidr) || (has(self.initProvider) && has(self.initProvider.destinationCidr))",message="spec.forProvider.destinationCidr is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nextHop) || (has(self.initProvider) && has(self.initProvider.nextHop))",message="spec.forProvider.nextHop is a required parameter"
	Spec   SubnetRouteSpec   `json:"spec"`
	Status SubnetRouteStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SubnetRouteList contains a list of SubnetRoutes
type SubnetRouteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SubnetRoute `json:"items"`
}

// Repository type metadata.
var (
	SubnetRoute_Kind             = "SubnetRoute"
	SubnetRoute_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SubnetRoute_Kind}.String()
	SubnetRoute_KindAPIVersion   = SubnetRoute_Kind + "." + CRDGroupVersion.String()
	SubnetRoute_GroupVersionKind = CRDGroupVersion.WithKind(SubnetRoute_Kind)
)

func init() {
	SchemeBuilder.Register(&SubnetRoute{}, &SubnetRouteList{})
}
